name: Site checker

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install w3c-linkchecker node-ws
    - name: Check websocket connection
      run: |
        wscat --version
        wscat --connect --help "wss://reanimate.clozecards.com:443/ws/"
    - name: Check links at reanimate.github.io
      run: |
        FAILURES=$(checklink --quiet --broken "https://reanimate.github.io/")
        if [ -n "$FAILURES" ]; then
          echo $FAILURES
          exit 1
        fi
